### ISSUE TITLE
Crash when entering elevator just after digging shaft

### ISSUE THREAD

**Issue by luk3yx** [shacknetisp/elevator#8]
The title should give enough information to fix this.

**Comment by ghost** [comment]
Is this still happening?

**Comment by luk3yx** [comment]
There have been [no code changes](https://github.com/shacknetisp/elevator/commits/master) since I reported the issue, so I assume it would still happen.

**Comment by ghost** [comment]
I can't reproduce it however. Probably need more details

**Comment by luk3yx** [comment]
It requires lag (or a bad connection), otherwise the elevator changes to an inactive elevator before anyone can enter it.

**Comment by shacknetisp** [comment]
Please include the crash report (backtrace) that Minetest prints to the console when this occurs.

**Comment by luk3yx** [comment]
> Please include the crash report (backtrace) that Minetest prints to the console when this occurs.

```
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): .../mods/elevator/components.lua:268: attempt to index local 'motor' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	.../mods/elevator/components.lua:268: in function 'on_rightclick'
ERROR[Main]: 	.../builtin/game/item.lua:417: in function <.../builtin/game/item.lua:410>
```

I will create a PR to fix this issue shortly.
